# Generated by Django 5.1.2 on 2025-03-14 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('membership_date', models.DateField(auto_now_add=True, verbose_name='Membership Date')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('member_id', models.CharField(max_length=20, unique=True, verbose_name='Member ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patron_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patron',
                'verbose_name_plural': 'Patrons',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='patrons_pat_email_bf0bb6_idx'), models.Index(fields=['member_id'], name='patrons_pat_member__9885ee_idx'), models.Index(fields=['last_name', 'first_name'], name='patrons_pat_last_na_0a0799_idx')],
            },
        ),
    ]
