# Generated by Django 5.1.2 on 2025-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patron', 'Patron'), ('librarian', 'Librarian')], default='patron', max_length=10, verbose_name='Role'),
        ),
    ]
